travis:
  secure:
    BINSTAR_TOKEN: Lo3lISvWV2Lp5LtczcFgZIp+HcSQdRDdbEDiKbaJZ9DxhCN1GqrQ5vtyEAQP9JINGnmyoyxvHte7/eosphWUSqVLkTeFXyglrBAXPFJk483tdd1XLhZd/xu0X/AG9prrkMAx5tp9mMNKYtu+MbzAnOg59q8efPNcnhqeoOCHVCgXWSBqPRyVquoF6dngLE0xxwQvoM5lBhqoeV1W+8oc8UcBO33wQvPqEiLF5FpFGbZNn5juSO9y5HjFwYnFOTArEA/ZbOXh3AHvMcxdDe/HIBPIGD+mFgZEZgd+ynm6rpXhd1YfZ25CAPS69e1hoyXp4m5uLjNU4OacIcU2G5Rk2Ac2yrr+yLIbH28OieUip634DHrjmrRbC/33g7GqHOTaBOdFpnCFD6cWJWfuEP8T34BRzPIeznvI2FaUVVA6jGQ1dl2dLpJWIzbDc7c3f1HgfHuVUTNN5yrFMu8X1lZVAn2d6E1u+gxf9JVBYT7QbpYWk5tZXnosOpe+W79jvqDh4NqVHIyEpGTG12mel9Y8uBL9NiSbdvsqeD+4Chh4p7JhS779Ufp4xW+xLemt0sVdeh6J38ZRB8FqyNMHr6nw0F/s+NQ5yYz+d775koteN7SfoHofsqwbU5D0YZXy502MS5xjH8ltFBfPwgB2sCYSYiho8TaKoNtrt6ok0r5ZA8Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
