travis:
  secure:
    BINSTAR_TOKEN: Yb51eZMsWdftdPv2fNv3FS8juUhD08/er8PitjYMT29JGnJVP25dt09TLSvkj2W+wKFIvPqOYOm4XtyWnoVOG44AH5FBRQc4y6bMPQOUWjqwjKHATHqzWz32QB/j0zIu60EadA6rZe82Q+xHMUogPGMVtOlYD25l7uVbnto56G2nPElc0x7BPUccoMIv56rY2NmW/xb5ufTw+HtfV1VUeFXbJ0jTuZk4gD8+5GIUE1Uuf5tahe1YoCnq7i1B456bILHMgW71SOEG7vPN6QjUahrrZD7Pac3k8UEP8xVe6cWxqApINDIMgzWHqR989YIezHl/eqjmv/zOK2gLOfaY8zikeOQSYZv6VGRcaOpwbvQSODKuun5BEIOrHL9GuUVJwvtbJcaxFfliB0w5PhFTIg1SeTpFYb7sG8Wa5s0qLymuFEQXjfbF+J3f3nQATChd4B4EgeD+cTOBnhlTXzlrAsH33pezAkVG0uavk3oORmv7Au0Z5/zwk9VB4yBVwEtFQHsIOGt+S9nnWpjHoY2XYP1rJ2VupjNu19ml5Xf2+T9TbXHtidG1PHZ66ojJ3DHmkNPkE0Xbmd9pxvAZpmkTY081cbwQaUMbV6WsAJgHbg6hMfjWJ8nPy1bTpH8OKcdzOZtSNVsra6ZZDBfzirsayY7bpB66XAvOpwVwQTcLrjc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
